server:
  port: 25000

spring:
  application:
    name: cubemall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8335
        port: 8719

  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis

